collections:
  businesses:
    output: true

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

pages: ./_businesses

sass:
  sass_dir: _scss
