backend:
  name: github
  repo: wabusiness/wa-business
  branch: master

media_folder: "images/uploads"

collections:
  - name: "site-pages"
    label: Site Pages
    files:
      - label: "Splash Page"
        name: "splash-page"
        file: "_data/splash.yml"
        fields:
          - label: "Body Content"
            name: "body_content"
            widget: "markdown"
      - label: "Terms of Service"
        name: "terms_of_service"
        file: "_data/terms_of_service.yml"
        fields:
          - label: "Content"
            name: "content"
            widget: "markdown"
